<#
.SYNOPSIS
    Builds (unless -SkipBuild) and installs the cppcoder binary, renamed
    to 'sarah-bin', into a user-local bin directory -- added to your PATH
    if it isn't there already. Also (re)installs a 'sarah' wrapper
    (sarah.cmd + sarah.ps1 on Windows, a shell script elsewhere) next to
    it, which rebuilds sarah-bin automatically whenever src/, include/,
    or CMakeLists.txt are newer than the installed binary before running
    it -- so plain `sarah ...` always reflects the latest source. No
    admin/sudo rights needed.

.PARAMETER SkipBuild
    Skip the build step and install whatever's already in build/.

.PARAMETER Clean
    Full rebuild first (forwarded to t.ps1 -Clean).

.PARAMETER Destination
    Directory to install the renamed binary into. Defaults to
    %LOCALAPPDATA%\Programs\sarah on Windows, or ~/.local/bin elsewhere.

.EXAMPLE
    ./install.ps1
    Build (if needed) and install as 'sarah' into the default user-local
    bin directory, adding that directory to PATH.

.EXAMPLE
    ./install.ps1 -SkipBuild
    Reuse the existing build/ and just (re)install.

.EXAMPLE
    ./install.ps1 -Clean -Destination ~/bin
    Full rebuild, then install into a custom directory.
#>

[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [switch]$Clean,
    [string]$Destination
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

# See t.ps1 for why this guards against Windows PowerShell 5.1 (Desktop
# edition), where $IsWindows doesn't exist.
if ($PSVersionTable.PSEdition -eq 'Core') {
    $OnWindows = $IsWindows
}
else {
    $OnWindows = $true
}

function Write-Step {
    param([string]$Message)
    Write-Host "==> $Message" -ForegroundColor Cyan
}

if (-not $SkipBuild) {
    Write-Step 'Building cppcoder (delegating to t.ps1)'
    # Hashtable splat, not array splat: array splatting binds positionally
    # (switches are excluded from position numbering, so a bare
    # '-SkipTests' string would land on t.ps1's first non-switch
    # parameter, $Jobs, and fail its int conversion). Only hashtable
    # splatting binds by parameter name.
    $buildArgs = @{ SkipTests = $true }
    if ($Clean) { $buildArgs['Clean'] = $true }
    & (Join-Path $PSScriptRoot 't.ps1') @buildArgs
    if ($LASTEXITCODE -ne 0) { throw 't.ps1 build failed' }
}

# Probe both single-config (build/src/cppcoder) and multi-config
# (build/src/Debug/cppcoder.exe) layouts -- same candidates t.ps1's
# Find-CppCoderExe checks, since -SkipBuild may be reusing a build/ made
# by an earlier, differently-configured run.
$exeName = if ($OnWindows) { 'cppcoder.exe' } else { 'cppcoder' }
$candidates = @(
    (Join-Path 'build' (Join-Path 'src' $exeName)),
    (Join-Path 'build' (Join-Path 'src' (Join-Path 'Debug' $exeName))),
    (Join-Path 'build' (Join-Path 'src' (Join-Path 'Release' $exeName)))
)
$sourceExe = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $sourceExe) {
    throw ("cppcoder executable not found (looked in: $($candidates -join ', ')) -- " +
           'build first (omit -SkipBuild).')
}

if (-not $Destination) {
    $Destination = if ($OnWindows) {
        Join-Path $env:LOCALAPPDATA 'Programs\sarah'
    }
    else {
        Join-Path $HOME '.local/bin'
    }
}
$Destination = [System.IO.Path]::GetFullPath($Destination)

if (-not (Test-Path $Destination)) {
    Write-Step "Creating $Destination"
    New-Item -ItemType Directory -Path $Destination -Force | Out-Null
}

$binName = if ($OnWindows) { 'sarah-bin.exe' } else { 'sarah-bin' }
$binPath = Join-Path $Destination $binName

Write-Step "Installing $sourceExe -> $binPath"
Copy-Item -Path $sourceExe -Destination $binPath -Force
if (-not $OnWindows) {
    chmod +x $binPath
}

# An older version of this script installed the real binary directly as
# 'sarah'/'sarah.exe'. On Windows that name now belongs to the wrapper
# (sarah.cmd) below -- but .EXE outranks .CMD in the default PATHEXT
# search order, so a leftover sarah.exe would silently keep shadowing the
# wrapper forever. Remove it so plain `sarah` actually resolves to the
# wrapper.
$staleDirectExe = Join-Path $Destination $(if ($OnWindows) { 'sarah.exe' } else { 'sarah' })
if ((Test-Path $staleDirectExe) -and $OnWindows) {
    Write-Step "Removing stale direct binary at $staleDirectExe (superseded by the sarah wrapper)"
    Remove-Item -Path $staleDirectExe -Force
}

# ---------------------------------------------------------------------------
# Install the 'sarah' wrapper: rebuild-if-stale, then exec sarah-bin.
# ---------------------------------------------------------------------------
if ($OnWindows) {
    $wrapperPs1Path = Join-Path $Destination 'sarah.ps1'
    $wrapperCmdPath = Join-Path $Destination 'sarah.cmd'

    $wrapperPs1 = @"
# Auto-generated by CppCoder's install.ps1 -- rerun install.ps1 to refresh.
param([Parameter(ValueFromRemainingArguments = `$true)][string[]]`$RestArgs)
`$ErrorActionPreference = 'Stop'
`$repoRoot = '$PSScriptRoot'
`$binExe = '$binPath'

`$sourceRoots = @(
    (Join-Path `$repoRoot 'src'),
    (Join-Path `$repoRoot 'include'),
    (Join-Path `$repoRoot 'CMakeLists.txt')
) | Where-Object { Test-Path `$_ }

`$newestSource = `$sourceRoots |
    ForEach-Object { Get-ChildItem -Path `$_ -Recurse -File -ErrorAction SilentlyContinue } |
    Sort-Object LastWriteTimeUtc -Descending |
    Select-Object -First 1 -ExpandProperty LastWriteTimeUtc
if (-not `$newestSource) { `$newestSource = [datetime]::MinValue }

`$binTime = if (Test-Path `$binExe) { (Get-Item `$binExe).LastWriteTimeUtc } else { [datetime]::MinValue }

if (`$newestSource -gt `$binTime) {
    Write-Host '==> sarah source changed -- rebuilding...' -ForegroundColor Cyan
    # -Jobs 4: t.ps1's own OOM-avoidance heuristic sizes parallelism off
    # *total* RAM, not what's currently free -- a conservative cap here
    # avoids clang-cl OOM crashes when other apps already hold most of it.
    & (Join-Path `$repoRoot 't.ps1') -SkipTests -Jobs 4
    if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }
    & (Join-Path `$repoRoot 'install.ps1') -SkipBuild
    if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }
}

& `$binExe @RestArgs
exit `$LASTEXITCODE
"@
    Set-Content -Path $wrapperPs1Path -Value $wrapperPs1 -Encoding UTF8

    $wrapperCmd = "@echo off`r`npowershell -NoProfile -ExecutionPolicy Bypass -File `"%~dp0sarah.ps1`" %*`r`n"
    Set-Content -Path $wrapperCmdPath -Value $wrapperCmd -Encoding ASCII -NoNewline

    Write-Step "Installed wrapper: $wrapperCmdPath (rebuilds from $PSScriptRoot when stale)"
}
else {
    $wrapperPath = Join-Path $Destination 'sarah'
    $wrapperScript = @"
#!/usr/bin/env bash
# Auto-generated by CppCoder's install.ps1 -- rerun install.ps1 to refresh.
repo_root='$PSScriptRoot'
bin_exe='$binPath'

newest_source=`$(find "`$repo_root/src" "`$repo_root/include" "`$repo_root/CMakeLists.txt" -type f -newer "`$bin_exe" 2>/dev/null | head -n1)
if [ ! -x "`$bin_exe" ] || [ -n "`$newest_source" ]; then
    echo '==> sarah source changed -- rebuilding...' >&2
    pwsh "`$repo_root/t.ps1" -SkipTests -Jobs 4 || exit `$?
    pwsh "`$repo_root/install.ps1" -SkipBuild || exit `$?
fi

exec "`$bin_exe" "`$@"
"@
    Set-Content -Path $wrapperPath -Value $wrapperScript -Encoding UTF8 -NoNewline
    chmod +x $wrapperPath

    Write-Step "Installed wrapper: $wrapperPath (rebuilds from $PSScriptRoot when stale)"
}

# ---------------------------------------------------------------------------
# Add $Destination to the user's PATH if it isn't already there.
# ---------------------------------------------------------------------------
function Add-DestinationToPath {
    param([string]$Dir)

    # Persisted PATH (registry 'User' scope / ~/.profile) and *this*
    # session's live $env:PATH are independent: the persisted value might
    # already include $Dir from an earlier install run, while this
    # session was started before that ever happened and so never picked
    # it up. Check and patch each separately -- checking only the
    # persisted value (as a previous version of this script did) means a
    # session opened before the first install run stays broken forever,
    # since "already on PATH" then skips patching $env:PATH here too.
    if ($OnWindows) {
        $currentPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
        $persistedEntries = @(($currentPath -split ';') | Where-Object { $_ })
        $addedToPersisted = $false
        if ($persistedEntries -notcontains $Dir) {
            $newPath = if ($currentPath) { "$currentPath;$Dir" } else { $Dir }
            [Environment]::SetEnvironmentVariable('PATH', $newPath, 'User')
            $addedToPersisted = $true
        }

        $sessionEntries = @(($env:PATH -split ';') | Where-Object { $_ })
        $addedToSession = $false
        if ($sessionEntries -notcontains $Dir) {
            $env:PATH = if ($env:PATH) { "$env:PATH;$Dir" } else { $Dir }
            $addedToSession = $true
        }

        if ($addedToPersisted) {
            Write-Step "Added $Dir to your PATH (open a new terminal to pick it up elsewhere)"
        }
        elseif ($addedToSession) {
            Write-Step "$Dir was already on your persisted PATH, but not this session's -- patched $env:PATH here too"
        }
        else {
            Write-Step "$Dir is already on PATH"
        }
        return
    }

    $persistedEntries = @(($env:PATH -split ':') | Where-Object { $_ })
    # ~/.profile is sourced by bash and zsh login shells alike, unlike
    # shell-specific rc files, so it's the one place that reliably picks
    # this up regardless of which shell the user runs `sarah` from next.
    $profileFile = Join-Path $HOME '.profile'
    $alreadyInProfile = (Test-Path $profileFile) -and
                        (Select-String -Path $profileFile -SimpleMatch $Dir -Quiet)
    if (-not $alreadyInProfile) {
        Add-Content -Path $profileFile -Value "`n# Added by CppCoder's install.ps1`nexport PATH=`"`$PATH:$Dir`""
    }

    if ($persistedEntries -notcontains $Dir) {
        $env:PATH = "$env:PATH:$Dir"
        Write-Step "Added $Dir to your PATH (start a new shell, or run: source ~/.profile, to pick it up elsewhere)"
    }
    else {
        Write-Step "$Dir is already on PATH"
    }
}

Add-DestinationToPath -Dir $Destination

Write-Step "Installed 'sarah' (wrapper) + '$binName'. This session can already run it -- try: sarah --help"
